In [2]:
import pandas as pd

data = {
"Name": [
    "Alice", "Bob", "Charlie", "David", "Evelyn",
    "Frank", "Grace", "Henry", "Isla", "Jack",
    "Karen", "Leo", "Mia", "Noah", "Olivia",
    "Paul", "Quinn", "Ruby", "Sam", "Tina"
],
"Age": [25, 32, 37, 29, 41, 28, 34, 45, 26, 31, 39, 27, 33, 36, 30, 42, 24, 38, 35, 29],
"Department": [
    "HR", "Engineering", "Sales", "Marketing", "Engineering",
    "Finance", "Support", "Operations", "HR", "Sales",
    "Engineering", "Support", "Marketing", "Finance", "Operations",
    "Engineering", "HR", "Sales", "Support", "Marketing"
],
"Salary": [
    50000, 75000, 62000, 58000, 80000,
    54000, 52000, 70000, 51000, 64000,
    82000, 53000, 60000, 56000, 68000,
    79000, 49500, 65500, 54500, 61000
],
}

df = pd.DataFrame(data)

### 1.Printing first five rows of DataFrame

In [3]:
df.head()

      Name  Age   Department  Salary
0    Alice   25           HR   50000
1      Bob   32  Engineering   75000
2  Charlie   37        Sales   62000
3    David   29    Marketing   58000
4   Evelyn   41  Engineering   80000

### 2.Printing last five rows of DataFrame

In [4]:
print(df.tail())

     Name  Age   Department  Salary
15   Paul   42  Engineering   79000
16  Quinn   24           HR   49500
17   Ruby   38        Sales   65500
18    Sam   35      Support   54500
19   Tina   29    Marketing   61000

### 3.Basic info about dataframe

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        20 non-null     str
 1   Age         20 non-null     int64
 2   Department  20 non-null     str
 3   Salary      20 non-null     int64
dtypes: int64(2), str(2)
memory usage: 772.0 bytes

### 4.Check the shape of data

In [7]:
df.shape

(20, 4)

In [8]:
type(df)

pandas.DataFrame

In [9]:
df.Age

0     25
1     32
2     37
3     29
4     41
5     28
6     34
7     45
8     26
9     31
10    39
11    27
12    33
13    36
14    30
15    42
16    24
17    38
18    35
19    29
Name: Age, dtype: int64

In [10]:
df['Age'].head()

0    25
1    32
2    37
3    29
4    41
Name: Age, dtype: int64

In [12]:
df[['Name', 'Salary', 'Department']].head()

      Name  Salary   Department
0    Alice   50000           HR
1      Bob   75000  Engineering
2  Charlie   62000        Sales
3    David   58000    Marketing
4   Evelyn   80000  Engineering

In [15]:
df[df['Age'] < 30]

     Name  Age Department  Salary
0   Alice   25         HR   50000
3   David   29  Marketing   58000
5   Frank   28    Finance   54000
8    Isla   26         HR   51000
11    Leo   27    Support   53000
16  Quinn   24         HR   49500
19   Tina   29  Marketing   61000

In [17]:
df[(df['Age'] < 30) & (df['Department'] == 'HR')]

     Name  Age Department  Salary
0   Alice   25         HR   50000
8    Isla   26         HR   51000
16  Quinn   24         HR   49500

In [18]:
df.loc[0]

Name          Alice
Age              25
Department       HR
Salary        50000
Name: 0, dtype: object

In [19]:
df.loc[0:2]

      Name  Age   Department  Salary
0    Alice   25           HR   50000
1      Bob   32  Engineering   75000
2  Charlie   37        Sales   62000

In [20]:
df.loc[0:2, ['Name', 'Age']]

      Name  Age
0    Alice   25
1      Bob   32
2  Charlie   37

In [21]:
df.iloc[0]

Name          Alice
Age              25
Department       HR
Salary        50000
Name: 0, dtype: object

In [22]:
df.iloc[0:3]

      Name  Age   Department  Salary
0    Alice   25           HR   50000
1      Bob   32  Engineering   75000
2  Charlie   37        Sales   62000

In [23]:
df.iloc[0:3, 0:2]

      Name  Age
0    Alice   25
1      Bob   32
2  Charlie   37